FROM node:lts-alpine
ENV NODE_ENV=production
WORKDIR /app
COPY . .
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 3000
VOLUME [ "/app/uploads", "/app/public", "/app/log" ]
CMD [ "node", "bin/www" ]
