FROM node:lts-alpine
ENV NODE_ENV=production
ENV DB_SERVER=host.docker.internal
WORKDIR /app
COPY . .
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 3000
VOLUME [ "/app/uploads", "/app/public", "/app/log" ]
CMD [ "node", "bin/www" ]

# docker build -t node-server .
# docker image rm node-server
# docker run --rm -d -v C:\Cursos\FS20231120\uploads:/app/uploads -v C:\Cursos\FS20231120\log:/app/log --name node-server-1 -p 8081:3000 node-server
# docker stop node-server-1
