@hostname = http://localhost:3000

GET {{hostname}}/saluda?Nombre=worl

###
GET {{hostname}}/saluda/user

###
GET {{hostname}}/saludar

###

GET {{hostname}}/saluda/666

###

GET {{hostname}}/saluda/666/despide

###

PUT {{hostname}}/saluda/666

###

post {{hostname}}/login
Content-Type: application/json
Accept: application/json

{
    "username": "json@example.com",
    "password": "P@$$w0rd"
}

###

post {{hostname}}/login
Content-Type: application/x-www-form-urlencoded

username=form@example.com&password=P@$$w0rd

###

post {{hostname}}/login
Content-Type: application/xml
Accept: application/json

<User>
    <username>json@example.com</username>
    <password>P@$$w0rd</password>
</User>
###

get {{hostname}}/stylesheets/style.css


###

get {{hostname}}/api/actores/v1?page=5&rows=10

###

get {{hostname}}/api/actores/v11/1/peliculas

###
# @name newActor
post {{hostname}}/api/actores
Content-Type: application/json

{
    "actorId": 222,
    "firstName": "PP",
    "lastName": "GRILLO"
}

###
# @name loadActor

get {{newActor.response.headers.location}}

###
put {{newActor.response.headers.location}}
Content-Type: application/json

{
    "actorId": {{loadActor.response.body.$.actorId}},
    "firstName": "PEPITO",
    "lastName": "GRILLO",
     "lastUpdate": "2023-11-23T00:00:00"
}

###

delete {{newActor.response.headers.location}}

###
post {{hostname}}/api/actores
Content-Type: application/json

{
    "actorId": 222,
    "firstName": 2,
    "lastName": 2
}

###
put {{hostname}}/api/actores/202
Content-Type: application/json

{
    "actorId": 202,
    "firstName": "1234567890123456789012345678901234567890a",
    "lastName": "2"
}

###
put {{hostname}}/api/actores/1
Content-Type: application/json

{
    "actorId": 222,
    "firstName": 2,
    "lastName": 2
}

###
get {{hostname}}/api/contactos
Content-Type: application/json

{
    "actorId": 222,
    "firstName": 2,
    "lastName": 2
}
