GET http://localhost:3000/saluda?Nombre=worl

###
GET http://localhost:3000/saluda/user

###
GET http://localhost:3000/saludar

###

GET http://localhost:3000/saluda/666

###

GET http://localhost:3000/saluda/666/despide

###

PUT http://localhost:3000/saluda/666

###

post http://localhost:3000/login
Content-Type: application/json
Accept: application/json

{
    "username": "json@example.com",
    "password": "P@$$w0rd"
}

###

post http://localhost:3000/login
Content-Type: application/x-www-form-urlencoded

username=form@example.com&password=P@$$w0rd

###

post http://localhost:3000/login
Content-Type: application/xml
Accept: application/json

<User>
    <username>json@example.com</username>
    <password>P@$$w0rd</password>
</User>

