GET http://localhost:3000/saluda?Nombre=worl

###
GET http://localhost:3000/saluda/user

###
GET http://localhost:3000/saludar

###

GET http://localhost:3000/saluda/666

###

GET http://localhost:3000/saluda/666/despide

###

PUT http://localhost:3000/saluda/666
